app:
  dataSource:
    postgres:
      port: 5432
      username: postgres
      password: password
      host: localhost
      databaseName: postgres-0
      jdbc-url: jdbc:postgresql://localhost:5432/postgres
