spring:
  datasource:
    postgres:
      url: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driver-class-name: org.postgresql.Driver
      schema: schoolconsoleapp

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

    flyway:
      defalul-schema: V1__init_migration.sql
      create-schemas: true

version: '3'

